//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Coalition
{
	public virtual int ID
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Premier
	{
		get;
		set;
	}

	public virtual Ellection Ellection
	{
		get;
		set;
	}

	public virtual List<Party> parties
	{
		get;
		set;
	}

	public virtual int Seats
	{
		get;
		set;
	}

	public virtual Ellection ellection
	{
		get;
		set;
	}

	public virtual bool EditCoalition(string name, string premier)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetID(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetEllection(Ellection ellection)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SetParties(List<Party> Parties)
	{
		throw new System.NotImplementedException();
	}

	public virtual string CalculatePremier()
	{
		throw new System.NotImplementedException();
	}

	public virtual int CalculateSeats()
	{
		throw new System.NotImplementedException();
	}

}

