//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Ellection
{
	public virtual DateTime BeginDate
	{
		get;
		set;
	}

	public virtual DateTime EndDate
	{
		get;
		set;
	}

	public virtual int ID
	{
		get;
		set;
	}

	public virtual bool Going
	{
		get;
		set;
	}

	public virtual int Seats
	{
		get;
		set;
	}

	public virtual string Kind
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual List<Party> parties
	{
		get;
		set;
	}

	public virtual List<Coalition> coalitions
	{
		get;
		set;
	}

	public virtual List<Result> results
	{
		get;
		set;
	}

	public virtual bool EditEllection(DateTime BeginDate, DateTime EndDate, bool Going, string Kind, string Name, int Seats)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetID(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool DeleteParty(Party Party)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool AddParty(Party Party)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool AddResults(Result Result)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ChangeResult(Result Result)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SetResult(Result Result)
	{
		throw new System.NotImplementedException();
	}

}

