//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Party
{
	public virtual int ID
	{
		get;
		set;
	}

	public virtual int Votes
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Represenitive
	{
		get;
		set;
	}

	public virtual Ellection ellection
	{
		get;
		set;
	}

	public virtual Result result
	{
		get;
		set;
	}

	public virtual bool EditParty(int name, string representitive, int votes)
	{
		throw new System.NotImplementedException();
	}
    public void SetID(int id)
    {
        ID = id;
    }
    public void SetVotes(int votes)
    {
        Votes = votes;
    }

}

